name: Typescript Check

on:
  push

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          cd Lyst
          npm install
          

      - name: Run typescript checks
        run: |
          cd Lyst
          npx tsc --noEmit